### ISSUE TITLE
Add full text search

### ISSUE THREAD

**Issue by tlnagy** [tlnagy/jekyll-lab-notebook#2]
I've looked into this a bit, but the main options all seem a bit limited since they don't highlight the section with the match. I might be able to do some ruby magic to split up log entries into separate "files" to trick these into working properly for the month-long logs.

- https://github.com/christian-fei/Simple-Jekyll-Search
- https://github.com/slashdotdash/jekyll-lunr-js-search
    - I might need to fork this one to get it to work since it creates its index internally

**Comment by tlnagy** [comment]
Actually, it looks like simple-jekyll-search can do full text search! https://github.com/christian-fei/Simple-Jekyll-Search/wiki#enabling-full-text-search so this should be pretty easy to implement.

**Comment by sebkopf** [comment]
thanks for providing such a great theme! the search via Simple-Jekyll-Search would definitely be super useful

**Comment by tlnagy** [comment]
The latest release adds full text search! 

![eln-full-text-search](https://user-images.githubusercontent.com/1661487/36184801-b7f87b4e-10ea-11e8-9437-9ffb0695f777.gif)
